[tools]
node = "25.4.0"

[tasks.dev]
run = "npm run dev"

[tasks.install]
run = "npm install"

[tasks.codegen]
run = "npm run relay"

[tasks.lint]
depends = ["lint:*"]

[tasks."lint:eslint"]
run = "npx eslint ."

[tasks.fmt]
depends = ["fmt:*"]

[tasks."fmt:prettier"]
run = "npx prettier --write ."

[tasks.test]
run = "npx playwright test"

[tasks.ci]
depends = ["lint", "test"]
