[tools]
node = "25.4.0"

[tasks."install:npm"]
run = "npm install"

[tasks."install:playwright"]
run = "npx playwright install --with-deps"

[tasks.install]
depends = ["install:*"]

[tasks."codegen:relay"]
run = "npm run relay"

[tasks.codegen]
depends = ["codegen:*"]

[tasks."lint:eslint"]
run = "npx eslint ."

[tasks."lint:prettier"]
run = "npx prettier --check ."

[tasks.lint]
depends = ["lint:*"]

[tasks."fmt:prettier"]
run = "npx prettier --write ."

[tasks.fmt]
depends = ["fmt:*"]

[tasks."test:playwright"]
run = "npx playwright test"

[tasks.test]
depends = ["test:*"]

[tasks.ci]
depends = ["lint", "test"]
