[tools]
node = "lts"

[tasks.dev]
run = "npm run dev"

[tasks.install]
run = "npm install && npx playwright install --with-deps"

[tasks.codegen]
run = "npm run relay"

[tasks.build]
run = "npm run build"

[tasks.lint]
depends = ["lint:*"]

[tasks."lint:eslint"]
run = "npx eslint ."

[tasks."lint:prettier"]
run = "npx prettier --check ."

[tasks.fmt]
depends = ["fmt:*"]

[tasks."fmt:prettier"]
run = "npx prettier --write ."

[tasks.test]
run = "npx playwright test"

[tasks.ci]
depends = ["lint", "test"]
